services:
    product_handler:
        class: Acme\ApiBundle\Handler\ProductHandler
        arguments: ["@security.token_storage", "@doctrine"]

    product_repository:
        class: Acme\ApiBundle\Entity\ProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Acme\ApiBundle\Entity\Product
    category_repository:
        class: Acme\ApiBundle\Entity\CategoryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Acme\ApiBundle\Entity\Category